<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container90fZyUZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container90fZyUZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container90fZyUZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container90fZyUZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container90fZyUZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '90fZyUZ',
    'container.build_id' => 'e6b07d7b',
    'container.build_time' => 1646903867,
], __DIR__.\DIRECTORY_SEPARATOR.'Container90fZyUZ');
